name: six_me_ludo_android
description: Ludo on Android.

publish_to: "none"

version: 1.3.0+6

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  assets_audio_player: ^3.0.5
  cached_network_image: ^3.2.2
  clipboard: ^0.1.3
  cloud_firestore: ^4.0.3
  confetti: ^0.7.0
  css_colors: ^1.1.1
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_database: ^10.0.3
  flex_color_scheme: ^6.0.0
  flutter_cache_manager: ^3.3.0
  firebase_dynamic_links: ^5.0.5
  flutter_fadein: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.4
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1
  jiffy: ^5.0.0
  lottie: ^1.4.2
  material_design_icons_flutter: ^5.0.6996
  multiavatar: ^0.1.5
  package_info_plus: ^3.0.1
  profanity_filter: ^2.0.0
  provider: ^6.0.3
  share_plus: ^6.2.0
  username_generator: ^1.3.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  visibility_detector: ^0.3.3
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/lottie/
    - assets/sounds/
    - assets/logo/
