name: six_me_ludo_android
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  get: ^4.6.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  firebase_database: ^9.1.3
  cloud_firestore: ^3.4.6
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  profanity_filter: ^2.0.0
  jiffy: ^5.0.0
  fluttertoast: ^8.0.9
  username_generator: ^1.3.0
  url_launcher: ^6.1.5
  flutter_staggered_animations: ^1.1.1
  badges: ^2.0.3
  flex_color_scheme: ^6.0.0
  loader_overlay: ^2.0.10
  http: ^0.13.5
  css_colors: ^1.1.1
  google_sign_in: ^5.4.1
  lottie: ^1.4.2
  package_info_plus: ^1.4.3+1
  line_icons: ^2.0.1
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.4
  multiavatar: ^0.1.5
  flag: ^6.0.0
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/lottie/
