name: six_me_ludo_android
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  get: ^4.6.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  firebase_database: ^9.1.3
  cloud_firestore: ^3.4.6
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/lottie/
